// <auto-generated />
using System;
using Argus.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Argus.Api.Database.Migrations
{
    [DbContext(typeof(ArgusDbContext))]
    partial class ArgusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Argus.Api.Database.Entities.AppName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("AppName");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_AppNames_AppName")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("AppNames", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.AppRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("RepositoryUrl");

                    b.Property<int?>("RepositoryTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_AppRepositories_RepositoryUrl")
                        .HasFilter("[IsEnabled] = 1");

                    b.HasIndex("RepositoryTypeId");

                    b.ToTable("AppRepositories", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.AppStageName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("StageName");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_AppStageNames_StageName")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("AppStageNames", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.ApplicationInstallation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppNameId")
                        .HasColumnType("int");

                    b.Property<int>("AppStageNameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DnsEndpointId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhysicalPathId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessorArchitectureId")
                        .HasColumnType("int");

                    b.Property<int>("RootPathId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidFromDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidToDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AppNameId");

                    b.HasIndex("AppStageNameId");

                    b.HasIndex("DnsEndpointId");

                    b.HasIndex("MachineId");

                    b.HasIndex("PhysicalPathId");

                    b.HasIndex("ProcessorArchitectureId");

                    b.HasIndex("RootPathId");

                    b.HasIndex("MachineId", "AppNameId", "AppStageNameId", "RootPathId")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationInstallations_Deployment")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("ApplicationInstallations", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ApplicationUsers", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.DnsEndpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLoadBalancer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("DnsName");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_DnsEndpoints_DnsName")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("DnsEndpoints", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.EntityJournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("ChangeSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Field")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("InstallationId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("NewValueId")
                        .HasColumnType("int");

                    b.Property<string>("OldValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("OldValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId", "ChangedUtc")
                        .HasDatabaseName("IX_EntityJournal_Installation");

                    b.ToTable("EntityJournal", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.InstallationRepository", b =>
                {
                    b.Property<int>("InstallationId")
                        .HasColumnType("int");

                    b.Property<int>("AppRepositoryId")
                        .HasColumnType("int");

                    b.HasKey("InstallationId", "AppRepositoryId");

                    b.HasIndex("AppRepositoryId");

                    b.ToTable("InstallationRepositories", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.InstallationTag", b =>
                {
                    b.Property<int>("InstallationId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("InstallationId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("InstallationTags", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("MachineName");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Machines_MachineName")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("Machines", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.PhysicalPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Path");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_PhysicalPaths_Path")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("PhysicalPaths", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.ProcessorArchitecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ArchitectureName");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ProcessorArchitectures_ArchitectureName")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("ProcessorArchitectures", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.RepositoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("RepositoryTypeName");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_RepositoryTypes_RepositoryTypeName")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("RepositoryTypes", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.RootPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Path");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_RootPaths_Path")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("RootPaths", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("TagName");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Tags_TagName")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.AppRepository", b =>
                {
                    b.HasOne("Argus.Api.Database.Entities.RepositoryType", "RepositoryType")
                        .WithMany("AppRepositories")
                        .HasForeignKey("RepositoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RepositoryType");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.ApplicationInstallation", b =>
                {
                    b.HasOne("Argus.Api.Database.Entities.AppName", "AppName")
                        .WithMany("Installations")
                        .HasForeignKey("AppNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Argus.Api.Database.Entities.AppStageName", "AppStageName")
                        .WithMany("Installations")
                        .HasForeignKey("AppStageNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Argus.Api.Database.Entities.DnsEndpoint", "DnsEndpoint")
                        .WithMany("Installations")
                        .HasForeignKey("DnsEndpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Argus.Api.Database.Entities.Machine", "Machine")
                        .WithMany("Installations")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Argus.Api.Database.Entities.PhysicalPath", "PhysicalPath")
                        .WithMany("Installations")
                        .HasForeignKey("PhysicalPathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Argus.Api.Database.Entities.ProcessorArchitecture", "ProcessorArchitecture")
                        .WithMany("Installations")
                        .HasForeignKey("ProcessorArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Argus.Api.Database.Entities.RootPath", "RootPath")
                        .WithMany("Installations")
                        .HasForeignKey("RootPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppName");

                    b.Navigation("AppStageName");

                    b.Navigation("DnsEndpoint");

                    b.Navigation("Machine");

                    b.Navigation("PhysicalPath");

                    b.Navigation("ProcessorArchitecture");

                    b.Navigation("RootPath");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.EntityJournalEntry", b =>
                {
                    b.HasOne("Argus.Api.Database.Entities.ApplicationInstallation", "Installation")
                        .WithMany("JournalEntries")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.InstallationRepository", b =>
                {
                    b.HasOne("Argus.Api.Database.Entities.AppRepository", "AppRepository")
                        .WithMany("InstallationRepositories")
                        .HasForeignKey("AppRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Argus.Api.Database.Entities.ApplicationInstallation", "Installation")
                        .WithMany("InstallationRepositories")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRepository");

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.InstallationTag", b =>
                {
                    b.HasOne("Argus.Api.Database.Entities.ApplicationInstallation", "Installation")
                        .WithMany("InstallationTags")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Argus.Api.Database.Entities.Tag", "Tag")
                        .WithMany("InstallationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Installation");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.AppName", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.AppRepository", b =>
                {
                    b.Navigation("InstallationRepositories");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.AppStageName", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.ApplicationInstallation", b =>
                {
                    b.Navigation("InstallationRepositories");

                    b.Navigation("InstallationTags");

                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.DnsEndpoint", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.Machine", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.PhysicalPath", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.ProcessorArchitecture", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.RepositoryType", b =>
                {
                    b.Navigation("AppRepositories");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.RootPath", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Argus.Api.Database.Entities.Tag", b =>
                {
                    b.Navigation("InstallationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
